/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ReferralLevel {
        /**
          * Referral level
         */
        "referralCount": number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLReferralLevelElement extends Components.ReferralLevel, HTMLStencilElement {
    }
    var HTMLReferralLevelElement: {
        prototype: HTMLReferralLevelElement;
        new (): HTMLReferralLevelElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "referral-level": HTMLReferralLevelElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ReferralLevel {
        /**
          * Referral level
         */
        "referralCount"?: number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "referral-level": ReferralLevel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "referral-level": LocalJSX.ReferralLevel & JSXBase.HTMLAttributes<HTMLReferralLevelElement>;
        }
    }
}
